title: Rako-tuto
# description: Un site avec plusieurs routes sur GitHub Pages.
baseurl: "" # Ne rien mettre si c'est le dépôt racine de GitHub Pages
url: "https://rako97460.github.io" # Remplacez par votre URL GitHub Pages

# Markdown et extensions
markdown: kramdown
theme: minima
